package com.calmomilla.domain.utils.enums;

public enum Especializacoes {
    PSICANALISE,
    PSICOLOGIA_PRETA_AFROPERSPECTIVADA,
    PSICOLOGIA_ESCOLAR,
    PSICOLOGIA_SOCIAL,
    PSICOTERAPIA_INDIVIDUAL,
    PSICOTERAPIA_ADOLESCENTES,
    PSICOTERAPIA_CRIANCAS,
    PSICOTERAPIA_ADULTOS,
    PSICOTERAPIA_IDOSOS,
    PSICOTERAPIA_CASAIS,
    PSICOTERAPIA_MULHERES_NEGRAS,
    GESTALT_TERAPIA,

}
